#!/usr/bin/env bash
# ============================================================================
# Creates the S3 bucket that holds OpenTofu state, then writes tf.sh.
#
# THE CHICKEN AND EGG: state has to live somewhere before the first apply, so
# the bucket that holds state cannot itself be managed by the state it holds.
# That is why this is a shell script and not a Tofu module. It runs ONCE per
# environment and is idempotent, so re-running it is safe.
#
#   ./create_tf_backend.sh dev
# ============================================================================
set -euo pipefail

ENV_DIR="${1:-dev}"
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
VALUES="$HERE/$ENV_DIR/global-values.yaml"

[[ -f "$VALUES" ]] || { echo "no such environment: $ENV_DIR (expected $VALUES)"; exit 1; }
command -v yq  >/dev/null || { echo "yq is required: https://github.com/mikefarah/yq"; exit 1; }
command -v aws >/dev/null || { echo "aws cli is required"; exit 1; }

REGION=$(yq -r '.global.aws_region' "$VALUES")
PREFIX=$(yq -r '.global.name_prefix' "$VALUES")

# Fail early with a clear message rather than 20 confusing AWS errors later.
ACCOUNT=$(aws sts get-caller-identity --query Account --output text 2>/dev/null) || {
  echo "AWS credentials are not valid. Run 'aws configure' (or 'aws sso login') first."
  exit 1
}

# The account id is in the name because S3 bucket names are GLOBALLY unique
# across every AWS account on earth. "shop-dev-tfstate" is almost certainly
# taken by someone; "shop-dev-123456789012-tfstate" is not.
BUCKET="${PREFIX}-${ACCOUNT}-tfstate"

echo "▸ account : $ACCOUNT"
echo "▸ region  : $REGION"
echo "▸ bucket  : $BUCKET"

if aws s3api head-bucket --bucket "$BUCKET" 2>/dev/null; then
  echo "  bucket already exists, leaving it alone"
else
  echo "  creating bucket"
  # us-east-1 is the one region that must NOT be given a
  # LocationConstraint -- passing it there is an InvalidLocationConstraint
  # error. Every other region requires it.
  if [[ "$REGION" == "us-east-1" ]]; then
    aws s3api create-bucket --bucket "$BUCKET" --region "$REGION"
  else
    aws s3api create-bucket --bucket "$BUCKET" --region "$REGION" \
      --create-bucket-configuration "LocationConstraint=$REGION"
  fi
fi

# Versioning: state files are overwritten on every apply. If one is ever
# written corrupt or truncated, versioning is the ONLY way back to a good
# copy. This is the single most important setting on this bucket.
echo "  enabling versioning"
aws s3api put-bucket-versioning --bucket "$BUCKET" \
  --versioning-configuration Status=Enabled

# State contains resource attributes in plain text. Encrypt at rest.
echo "  enabling default encryption"
aws s3api put-bucket-encryption --bucket "$BUCKET" \
  --server-side-encryption-configuration \
  '{"Rules":[{"ApplyServerSideEncryptionByDefault":{"SSEAlgorithm":"AES256"},"BucketKeyEnabled":true}]}'

# Block public access on a bucket full of infrastructure state. Belt and
# braces -- it is private by default, but this makes it impossible to
# accidentally make public later.
echo "  blocking all public access"
aws s3api put-public-access-block --bucket "$BUCKET" \
  --public-access-block-configuration \
  'BlockPublicAcls=true,IgnorePublicAcls=true,BlockPublicPolicy=true,RestrictPublicBuckets=true'

cat > "$HERE/tf.sh" <<EOF
# Generated by create_tf_backend.sh -- source this before running terragrunt:
#   source ./tf.sh
export AWS_REGION=$REGION
export TF_STATE_BUCKET=$BUCKET
EOF

echo
echo "✔ wrote $HERE/tf.sh"
echo "  next:  source ./tf.sh && ./provision.sh $ENV_DIR"
