#!/usr/bin/env bash
# Usage:
#   ./scripts/bootstrap.sh create       # create GCS bucket + write backend.hcl
#   ./scripts/bootstrap.sh delete       # delete GCS bucket + remove backend.hcl
#   ./scripts/bootstrap.sh enable-apis  # run terragrunt plan + apply for apis module

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

source "$REPO_ROOT/infra/config.env"

BUCKET_NAME="${ENV_NAME}-${APP_NAME}-backend-${BUCKET_SUFFIX}"
ENV_DIR="$REPO_ROOT/infra/${ENV_NAME}"
BACKEND_HCL="$ENV_DIR/backend.hcl"

create() {
  mkdir -p "$ENV_DIR"

  if gcloud storage buckets describe "gs://${BUCKET_NAME}" \
       --project="${GCP_PROJECT_ID}" &>/dev/null; then
    echo "Bucket gs://${BUCKET_NAME} already exists — skipping"
  else
    gcloud storage buckets create "gs://${BUCKET_NAME}" \
      --project="${GCP_PROJECT_ID}" \
      --location="${GCP_REGION}" \
      --uniform-bucket-level-access
    echo "Bucket created: gs://${BUCKET_NAME}"
  fi

  gcloud storage buckets update "gs://${BUCKET_NAME}" --versioning
  echo "Versioning enabled"

  cat > "$BACKEND_HCL" <<EOF
# Generated by scripts/bootstrap.sh — do not edit manually

locals {
  project_id   = "${GCP_PROJECT_ID}"
  region       = "${GCP_REGION}"
  env_name     = "${ENV_NAME}"
  app_name     = "${APP_NAME}"
  state_bucket = "${BUCKET_NAME}"
}
EOF

  echo "Written: ${BACKEND_HCL}"
  echo "Done. State bucket: gs://${BUCKET_NAME}"
}

delete() {
  echo "WARNING: this deletes all OpenTofu state. Only run after infra is destroyed."
  echo -n "Type 'yes' to confirm: "
  read -r confirm
  [[ "$confirm" != "yes" ]] && { echo "Cancelled."; exit 0; }

  if gcloud storage buckets describe "gs://${BUCKET_NAME}" \
       --project="${GCP_PROJECT_ID}" &>/dev/null; then
    gcloud storage rm -r "gs://${BUCKET_NAME}" --project="${GCP_PROJECT_ID}"
    echo "Bucket deleted: gs://${BUCKET_NAME}"
  else
    echo "Bucket gs://${BUCKET_NAME} not found — skipping"
  fi

  [[ -f "$BACKEND_HCL" ]] && rm "$BACKEND_HCL" && echo "Removed: ${BACKEND_HCL}"
}

# ── Helper: runs terragrunt plan then apply inside a given module directory ────
run_module() {
  local module_dir="$1"

  echo "--- plan ---"
  cd "$module_dir"
  terragrunt plan

  echo ""
  echo -n "Apply? (yes/no): "
  read -r confirm
  [[ "$confirm" != "yes" ]] && { echo "Cancelled."; exit 0; }

  terragrunt apply --auto-approve
  echo "Done."
}

enable_apis() {
  run_module "$ENV_DIR/apis"
}

create_network() {
  run_module "$ENV_DIR/network"

  # Read the static IP from the network module output
  local static_ip
  static_ip=$(cd "$ENV_DIR/network" && terragrunt output -raw ingress_static_ip 2>/dev/null)

  if [[ -z "$static_ip" ]]; then
    echo "WARNING: could not read ingress_static_ip — skipping global-vars.yaml"
    return
  fi

  # Write global-vars.yaml so downstream Helm deployments can reference the static IP
  local global_vars="$REPO_ROOT/vault-automation/global-vars.yaml"
  cat > "$global_vars" <<EOF
# Generated by scripts/bootstrap.sh after network module apply.
# Do not edit manually — re-run: ./scripts/bootstrap.sh create-network

global:
  static_ip: "${static_ip}"
EOF

  echo "Written: vault-automation/global-vars.yaml"
  echo "  static_ip: ${static_ip}"
}

create_gke() {
  run_module "$ENV_DIR/gke"
}

case "${1:-create}" in
  create)         create ;;
  delete)         delete ;;
  enable-apis)    enable_apis ;;
  create-network) create_network ;;
  create-gke)     create_gke ;;
  *)
    echo "Usage: $(basename "$0") [create|delete|enable-apis|create-network|create-gke]"
    exit 1
    ;;
esac
