apiVersion: v1
kind: Service
metadata:
  name: {{ include "shop-web.fullname" . }}
  labels: {{- include "shop-web.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}   # what callers use (80)
      targetPort: http                   # -> container port 8080
      protocol: TCP
      name: http
  selector: {{- include "shop-web.selectorLabels" . | nindent 4 }}
